spring:
  application:
    name: lockbox
  
  profiles:
    active: dev
    
  main:
    banner-mode: CONSOLE
    log-startup-info: false

  shell:
    interactive:
      enabled: true

# Logging pattern stays the same
logging:
  pattern:
    console: "%clr(%msg){faint}%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"