# Custom Nitrite Property (Hidden in Home)
lockbox:
  path: ${user.home}/.lockbox/lockbox.db

logging:
  file:
    name: ${user.home}/.lockbox/logs/lockbox.log
  level:
    root: WARN
    '[org.inn.lockbox]': INFO # Only show app-specific info
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 30
      total-size-cap: 100MB