# Custom Nitrite Property
lockbox:
  path: ./db/dev-lockbox.db

logging:
  file:
    name: ./logs/dev-lockbox.log
  level:
    root: INFO
    '[org.springframework]': WARN
    '[org.inn.lockbox]': DEBUG # High visibility for development